services:
  frontend:
    image: "code-capsule-frontend:latest"
    ports:
      - "3000:3000"
  api:
    image: "code-capsule-api:latest"
    ports:
      - "4001:4001"
    environment:
      MONGO_URI: "mongodb://mongoadmin:Gru@db:27017"
  db:
    image: "mongo:latest"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: Gru